import Mutations from "./mutations.js";
import Actions from "./actions.js";
import Getters from "./getters.js";

export default {
  namespaced: true,
  state: {
    users: [
      {
        userId: 1,
        username: "TestUser",
        password: "password123",
        role: 0,
        email: "user@example.com",
        firstName: "Max",
        lastName: "Usermann",
        numberLoans: 0,
        numberExtensions: 0,
        numberMissedReturns: 0,
        notifications: [],
      },
      {
        userId: 2,
        username: "TestManager",
        password: "password123",
        role: 1,
        email: "user@example.com",
        firstName: "Max",
        lastName: "Managermann",
        notifications: [
          {
            notificationId: "jm1fr3a2vqkluuzgkiy",
            type: 5,
            title: "Anfrage zur Verlängerung einer Ausleihe",
            message:
              "TestUser hat eine Verlängerung der Ausleihe von Lord of the Rings The Two Towers bis zum 14.4.2024 angefragt",
            senderId: 1,
            senderName: "TestUser",
            receiverId: 2,
            date: "11.4.2024",
            payload: { loanId: 2, userId: 1, newDueDate: "2024-04-14" },
          },
        ],
      },
      {
        userId: 3,
        username: "TestAdmin",
        password: "password123",
        role: 2,
        email: "user@example.com",
        firstName: "Max",
        lastName: "Adminmann",
        notifications: [],
      },
      {
        userId: 4,
        username: "TestUser2",
        password: "password123",
        role: 0,
        email: "user@example.com",
        firstName: "Anna",
        lastName: "Usermann2",
        numberLoans: 1,
        numberExtensions: 2,
        numberMissedReturns: 3,
        notifications: [],
      },
      {
        userId: 5,
        username: "TestUser3",
        password: "password123",
        role: 0,
        email: "user@example.com",
        firstName: "Hans",
        lastName: "Usermann3",
        numberLoans: 3,
        numberExtensions: 1,
        numberMissedReturns: 2,
        notifications: [],
      },
    ],
    userIsAuth: false,
    user: {
      userId: null,
      username: null,
      password: null,
      role: null,
      email: null,
      firstName: null,
      lastName: null,
      notifications: [],
    },
  },
  mutations: Mutations,
  actions: Actions,
  getters: Getters,
};
